services:
  wg-node:
    container_name: wg-node
    build: ./
    env_file: .env
    environment:
      NODE_ROOT_API_USER_PUBLIC_KEY_FILE: /run/secrets/node/root_api_user_public_key

      WIREGUARD_PUBLIC_PORT: 51820  # remember to update the ports section when updating this env var

      MONGO_HOST: wg-node-mongo
      MONGO_PORT: 27017
      MONGO_USERNAME_FILE: /run/secrets/mongo/username
      MONGO_PASSWORD_FILE: /run/secrets/mongo/password
      MONGO_DATABASE_FILE: /run/secrets/mongo/database

    volumes:
      - /etc/wg-node/:/etc/wg-node/  # wg-node persistent server key storage

    ports:
      - "51820:51820/udp"  # Wireguard UDP port
      - "51821:51821/tcp"  # Wireguard TCP port
      - "80:8080"          # web server HTTP port

    restart: unless-stopped

    depends_on:
      - wg-node-mongo

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

    secrets:
      - mongo
      - node

  wg-node-mongo:
    image:
      mongo
    container_name: wg-node-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo/username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo/password
      MONGO_INITDB_DATABASE_FILE: /run/secrets/mongo/database

    volumes:
      - ./.mongo-data:/data/db

    secrets:
      - mongo

#    ports:
#      - "27017:27017"

secrets:
  node:
    file: secrets/node/

  mongo:
    file: secrets/mongo/
